language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -y g++-6 python3-pip
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  - pip3 install keras
  - python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
script: 
  # Build and run this project
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - python3 ../python_model.py
  - ./keras2cpp
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 